### ISSUE TITLE
Update to TFJS version 1.1.2

### ISSUE THREAD

**Issue by hpssjellis** [mwdchang/tfjs-gan#2]
Great example. I really appreciate the live githubPages pure javascript format.

Getting zeroslike errors when updating to TFJS v1.1.2 any suggestions? 

Works fine on Version 0.15.3, but breaks at Version 1.0.0

**Comment by BenjaminWegener** [comment]
https://github.com/tensorflow/tfjs/issues/1398#issuecomment-490806579

**Comment by mwdchang** [comment]
Thanks for the report/information! 
Will play around with upgrading options when there's some free time on the weekends.

**Comment by BenjaminWegener** [comment]
https://github.com/tensorflow/tfjs/issues/1211#issuecomment-491829787

**Comment by mwdchang** [comment]
Bumped to 1.2.2
